name: Runner Test

on:
  workflow_dispatch:

jobs:
  runner-test:
    runs-on: self-hosted

    steps:
      - name: Test Ubuntu Runner
        run: |
          echo "================================"
          echo "GitHub Actions fonctionne !"
          echo "================================"
          echo "Machine :"
          hostname
          echo "Utilisateur :"
          whoami
          echo "OS :"
          uname -a
          echo "Docker :"
          docker --version
          echo "Date :"
          date