  runner-test:
    runs-on: self-hosted

    steps:

      - name: Test Ubuntu Runner
        run: |
          echo "===== SELF-HOSTED RUNNER ====="
          echo "Hostname:"
          hostname
          echo "User:"
          whoami
          echo "Docker:"
          docker --version
          echo "Docker Compose:"
          docker compose version